### PR TITLE
Add a note about the `SFMono-Regular` font requirement and how to get it

### PR DESCRIPTION
**Pull request by kschmidtdev**
`SFMono-Regular` appears to also be a required font - I've added note about that and how to install it! (I don't think we are allowed to distribute it so I simplified the instructions as much as I could)

### CODE REVIEW

**Comment by bengroulx** [comment]
We should use Roboto Mono instead, as that can be downloaded from the same spot as Roboto.

**Comment by kschmidtdev** [comment]
@bengroulx I'm not sure how that is relevant to my PR? `Roboto Mono` is already/still listed.

**Comment by jackygilbertson** [comment]
SFMono-Regular is not actually a required font.

**Comment by kschmidtdev** [comment]
So I can ignore Sketch asking for it when I open the UI Kit?

**Pull request closed without merging**
