### PR TITLE
[BASE] Added components, refined naming

### PR DESCRIPTION
**Pull request by jackygilbertson**
### Changes
- [x] Updated naming convention to match React component naming (from `pw-component-name` to `ComponentName`)
- [x] Rejigged the `Field` component to take better advantage of Sketch's new symbol switching
- [x] Tested and anchored interior objects in symbols to make them more flexible.
- [x] Combined `Swatch` and `Chip` into one component: `Swatch`
- [x] Updated icon symbols to export correct names instead of all of them being `dark.svg`
- [x] Added `Menu` component symbols.
- [x] Added `ActionList` component symbols.
- [x] Added `DatePicker` components.
- [x] Added "Page Count" variant for `Pagination`
- [x] Added Skeleton components: `SkeletonBlock`, `SkeletonText`
- [x] Added PDP example template
- [x] Delete "Experiments" page

### To Do
- [x] Designer Review

### CODE REVIEW

**Comment by jackygilbertson** [comment]
In the future we may explore more complex solutions for icons, but for now I've settled for simply renaming each icon.

**Comment by billjchung** [comment]
@jackygilbertson the *separator text, border* has a style on it with a 36pt white border..not sure if intentional (or maybe I'm missing something)

Also, I am curious if we should reassess come of the product tile layouts to have the group resizing options set to pin instead of resize (for example, the title layer is set to be resize, where maybe having it pinned might be more useful?) Likewise on the product tile rows, perhaps the labels should float in place versus resize so they remain vertically centred?

Just my thoughts.

**Comment by jackygilbertson** [comment]
@billjchung 

The border to the separator text is indeed intentional, as it allows the designer to add whatever text they like to the separator—beyond just "or"—with a flexible "gap" behind it; it had to be done like this because of how Sketch handles borders and shadows for text (borders are fixed to "center" so they eat into the text, and shadows have no "spread" option).

The tiles and their styles have been tested for maximum flexibility (within what Sketch can do), and these options were chosen for preserving the appearance as you resize them. It's also worth remembering that these are "default" examples, simply a starting point, not a definitive layout.

Does that answer your questions?

**Comment by billjchung** [comment]
@jackygilbertson fair enough, your reasons make sense. LGTM 👍

**Pull request merged**
